// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOLzFdRqnFP1tTDOMh5UOHVh8xDabqf4',
    appId: '1:661852163614:web:656f2b1e03009503a1e80f',
    messagingSenderId: '661852163614',
    projectId: 'zapp-geogenius',
    authDomain: 'zapp-geogenius.firebaseapp.com',
    storageBucket: 'zapp-geogenius.firebasestorage.app',
    measurementId: 'G-H5QZ317T8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkG0fyN-5GulHG3BrY2AlXSJhstKttqM8',
    appId: '1:661852163614:android:958b3cada2a1f3f7a1e80f',
    messagingSenderId: '661852163614',
    projectId: 'zapp-geogenius',
    storageBucket: 'zapp-geogenius.firebasestorage.app',
  );
}
